/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Zmiana ról użytkownika
         * @description Zastępuje role użytkownika podanym zestawem. Operacja audytowana (ROLE_CHANGE).
         */
        put: operations["updateUserRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rejestracja nowego użytkownika
         * @description Tworzy nowe (nieaktywne) konto i wysyła na podany adres e-mail wiadomość z linkiem aktywacyjnym. Konto wymaga aktywacji przed pierwszym logowaniem.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Żądanie resetu hasła
         * @description Jeśli konto o podanym adresie istnieje, wysyła wiadomość z linkiem do resetu hasła. Odpowiedź jest zawsze 200 (brak enumeracji użytkowników).
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Potwierdzenie resetu hasła
         * @description Ustawia nowe hasło na podstawie jednorazowego tokenu resetu (JWT). Po użyciu token jest unieważniany, a istniejące sesje użytkownika odwoływane.
         */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wylogowanie użytkownika
         * @description Unieważnia bieżący token dostępowy (blacklist) oraz wszystkie tokeny odświeżające użytkownika i czyści ciasteczko refreshToken.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logowanie użytkownika
         * @description Uwierzytelnia użytkownika i zwraca token dostępowy w ciele odpowiedzi. Token odświeżający (refresh) jest ustawiany jako bezpieczne ciasteczko HttpOnly o ścieżce /api/v1/auth/refresh.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/activation/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ponowne wysłanie wiadomości aktywacyjnej
         * @description Jeśli konto istnieje i nie jest jeszcze aktywne, wysyła nowy link aktywacyjny (poprzedni token zostaje zastąpiony). Odpowiedź jest zawsze 200 (brak enumeracji użytkowników).
         */
        post: operations["resendActivationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/force-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wymuszenie wylogowania
         * @description Unieważnia wszystkie aktywne sesje (tokeny) użytkownika bez zmiany stanu konta. Operacja audytowana (FORCE_LOGOUT).
         */
        post: operations["forceLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Aktualizacja profilu
         * @description Częściowo aktualizuje profil zalogowanego użytkownika. Przesyłane są tylko pola do zmiany; pominięte pozostają bez zmian.
         */
        patch: operations["profile"];
        trace?: never;
    };
    "/api/v1/admin/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Dezaktywacja konta
         * @description Wyłącza konto użytkownika i natychmiast unieważnia jego tokeny. Operacja audytowana (DEACTIVATE).
         */
        patch: operations["deactivateUser"];
        trace?: never;
    };
    "/api/v1/admin/users/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Aktywacja (reaktywacja) konta
         * @description Ponownie włącza wcześniej dezaktywowane konto. Operacja audytowana (ACTIVATE). Uwaga: poprzednie sesje pozostają unieważnione — wymagane ponowne logowanie.
         */
        patch: operations["activateUser"];
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dane zalogowanego użytkownika
         * @description Zwraca dane konta i profil aktualnie uwierzytelnionego użytkownika (na podstawie tokenu dostępowego).
         */
        get: operations["me"];
        put?: never;
        post?: never;
        /**
         * Usunięcie własnego konta
         * @description Trwale (hard delete) usuwa konto zalogowanego użytkownika po potwierdzeniu hasłem. Operacja jest nieodwracalna: unieważnia wszystkie tokeny odświeżające i bieżący token dostępowy oraz czyści ciasteczko refreshToken. Ostatni administrator nie może usunąć własnego konta.
         */
        delete: operations["deleteOwnAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Odświeżenie tokenu dostępowego
         * @description Na podstawie ważnego tokenu odświeżającego (ciasteczko refreshToken) wydaje nowy token dostępowy oraz rotuje token odświeżający.
         */
        get: operations["refreshAccessToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aktywacja konta
         * @description Aktywuje konto na podstawie jednorazowego tokenu aktywacyjnego (JWT) z linku wysłanego mailem. Po użyciu token jest unieważniany (blacklist).
         */
        get: operations["activateAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobierz użytkownika po identyfikatorze */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        /**
         * Usunięcie konta
         * @description Trwale usuwa konto użytkownika i unieważnia jego tokeny. Operacja audytowana (DELETE).
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/by-username/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobierz użytkownika po nazwie użytkownika */
        get: operations["getUserByUsername"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/by-email/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobierz użytkownika po adresie e-mail */
        get: operations["getUserByEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista użytkowników (stronicowana)
         * @description Zwraca stronicowaną listę wszystkich użytkowników. Parametry stronicowania: page, size, sort.
         */
        get: operations["getAllUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Przeszukiwanie dziennika audytu
         * @description Zwraca stronicowaną listę wpisów audytu z opcjonalnym filtrowaniem po użytkowniku, administratorze, rodzaju operacji i zakresie czasu. Domyślne sortowanie: createdAt malejąco.
         */
        get: operations["getAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Zestaw ról do przypisania użytkownikowi (zastępuje dotychczasowe role). */
        UpdateUserRolesDto: {
            /**
             * @description Niepusty zbiór nazw ról z prefiksem ROLE_.
             * @example [
             *       "ROLE_USER",
             *       "ROLE_ADMIN"
             *     ]
             */
            roles: string[];
        };
        ApiValidationError: {
            errorCode?: string;
            message?: string;
            errors?: components["schemas"]["FieldValidationError"][];
        };
        FieldValidationError: {
            field?: string;
            message?: string;
        };
        ApiError: {
            errorCode?: string;
            message?: string;
        };
        /** @description Adres użytkownika. */
        AddressDto: {
            /**
             * @description Ulica wraz z numerem.
             * @example Marszałkowska 1
             */
            street?: string;
            /**
             * @description Miasto.
             * @example Warszawa
             */
            city?: string;
            /**
             * @description Kod pocztowy.
             * @example 00-001
             */
            postalCode?: string;
            /**
             * @description Kraj.
             * @example Poland
             */
            country?: string;
        };
        /** @description Profil użytkownika zwracany w odpowiedziach. */
        UserProfileResponseDto: {
            /**
             * @description Imię.
             * @example John
             */
            firstName?: string;
            /**
             * @description Nazwisko.
             * @example Doe
             */
            lastName?: string;
            /**
             * @description Numer telefonu w formacie E.164.
             * @example +48123456789
             */
            phoneNumber?: string;
            /** @description Adres użytkownika. */
            address?: components["schemas"]["AddressDto"];
            /**
             * Format: date
             * @description Data urodzenia (ISO YYYY-MM-DD).
             * @example 1990-05-15
             */
            dateOfBirth?: string;
            /**
             * @description URL zdjęcia profilowego.
             * @example https://example.com/avatar.png
             */
            profilePictureUrl?: string;
        };
        /** @description Reprezentacja użytkownika zwracana przez API. */
        UserResponseDto: {
            /**
             * Format: uuid
             * @description Identyfikator użytkownika (UUID).
             * @example 018f4e2a-7c1d-7a3b-9b2e-0a1b2c3d4e5f
             */
            id: string;
            /**
             * @description Nazwa użytkownika.
             * @example john.doe
             */
            username: string;
            /**
             * @description Adres e-mail.
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Czy konto jest aktywne.
             * @example true
             */
            enabled: boolean;
            /**
             * @description Role przypisane użytkownikowi (z prefiksem ROLE_).
             * @example [
             *       "ROLE_USER"
             *     ]
             */
            roles: string[];
            /** @description Profil użytkownika. */
            profile: components["schemas"]["UserProfileResponseDto"];
        };
        /** @description Dane rejestracji nowego konta użytkownika. */
        RegistrationDto: {
            /**
             * @description Nazwa użytkownika: 3-30 znaków, dozwolone litery, cyfry oraz znaki . _ -
             * @example john.doe
             */
            username: string;
            /**
             * Format: email
             * @description Adres e-mail w poprawnym formacie. Na ten adres trafi link aktywacyjny.
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Hasło: minimum 8 znaków.
             * @example password123
             */
            password: string;
        };
        /** @description Prosta odpowiedź informacyjna z komunikatem dla klienta. */
        MessageResponseDto: {
            /**
             * @description Komunikat informacyjny dla klienta.
             * @example User registration successful. Please check your email to confirm your account.
             */
            message: string;
        };
        /** @description Żądanie wysłania linku do resetu hasła. */
        PasswordResetRequestDto: {
            /**
             * Format: email
             * @description Adres e-mail konta, dla którego ma zostać zresetowane hasło.
             * @example john.doe@example.com
             */
            email: string;
        };
        /** @description Potwierdzenie resetu hasła z tokenem otrzymanym mailem oraz nowym hasłem. */
        PasswordResetConfirmDto: {
            /**
             * @description Token resetu hasła (JWT) otrzymany w wiadomości e-mail.
             * @example eyJhbGciOiJIUzI1NiJ9...
             */
            token: string;
            /**
             * @description Nowe hasło: minimum 8 znaków.
             * @example newPassword1
             */
            newPassword: string;
        };
        /** @description Dane logowania użytkownika. */
        LoginDto: {
            /**
             * Format: email
             * @description Adres e-mail konta.
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Hasło konta.
             * @example password123
             */
            password: string;
        };
        /** @description Odpowiedź z tokenem dostępowym po zalogowaniu lub odświeżeniu sesji. */
        AccessTokenResponseDto: {
            /**
             * @description Token dostępowy JWT (ważny 15 min). Przekazuj w nagłówku `Authorization: Bearer <token>`.
             * @example eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIn0.5f1c...
             */
            accessToken: string;
        };
        /** @description Żądanie ponownego wysłania wiadomości aktywacyjnej. */
        ResendActivationEmailDto: {
            /**
             * Format: email
             * @description Adres e-mail konta, na który ma zostać ponownie wysłany link aktywacyjny.
             * @example john.doe@example.com
             */
            email: string;
        };
        /** @description Dane do częściowej aktualizacji profilu zalogowanego użytkownika. Wszystkie pola są opcjonalne — przesyłane są tylko te, które mają zostać zmienione. */
        UserProfileUpdateDto: {
            /**
             * @description Imię (maks. 50 znaków).
             * @example John
             */
            firstName?: string;
            /**
             * @description Nazwisko (maks. 50 znaków).
             * @example Doe
             */
            lastName?: string;
            /**
             * @description Numer telefonu w formacie E.164.
             * @example +48123456789
             */
            phoneNumber?: string;
            /** @description Adres użytkownika. */
            address?: components["schemas"]["AddressDto"];
            /**
             * Format: date
             * @description Data urodzenia w formacie ISO (YYYY-MM-DD); musi być w przeszłości.
             * @example 1990-05-15
             */
            dateOfBirth?: string;
            /**
             * @description URL zdjęcia profilowego (maks. 512 znaków).
             * @example https://example.com/avatar.png
             */
            profilePictureUrl?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        /** @description Stronicowana lista użytkowników. */
        PageUserResponseDto: {
            /** @description Zawartość bieżącej strony. */
            content: components["schemas"]["UserResponseDto"][];
            /**
             * Format: int32
             * @description Numer bieżącej strony (od 0).
             * @example 0
             */
            number: number;
            /**
             * Format: int32
             * @description Rozmiar strony.
             * @example 20
             */
            size: number;
            /**
             * Format: int64
             * @description Łączna liczba elementów.
             * @example 42
             */
            totalElements: number;
            /**
             * Format: int32
             * @description Łączna liczba stron.
             * @example 3
             */
            totalPages: number;
            /**
             * @description Czy to pierwsza strona.
             * @example true
             */
            first: boolean;
            /**
             * @description Czy to ostatnia strona.
             * @example false
             */
            last: boolean;
            /**
             * Format: int32
             * @description Liczba elementów na bieżącej stronie.
             * @example 20
             */
            numberOfElements: number;
            /**
             * @description Czy strona jest pusta.
             * @example false
             */
            empty: boolean;
        };
        /** @description Wpis dziennika audytu operacji na kontach użytkowników. */
        AuditLogResponseDto: {
            /**
             * Format: int64
             * @description Identyfikator wpisu.
             * @example 1024
             */
            id: number;
            /**
             * @description Rodzaj operacji.
             * @example ROLE_CHANGE
             * @enum {string}
             */
            action: "ROLE_CHANGE" | "DEACTIVATE" | "ACTIVATE" | "DELETE" | "FORCE_LOGOUT" | "PASSWORD_CHANGE";
            /**
             * Format: uuid
             * @description Identyfikator (UUID) użytkownika, którego dotyczy operacja.
             * @example 018f4e2a-7c1d-7a3b-9b2e-0a1b2c3d4e5f
             */
            targetId: string;
            /**
             * @description E-mail użytkownika, którego dotyczy operacja (wartość skopiowana w chwili zdarzenia).
             * @example jane.smith@example.com
             */
            targetEmail: string;
            /**
             * @description E-mail administratora wykonującego operację (dla operacji self-service równy targetEmail).
             * @example john.doe@example.com
             */
            actor: string;
            /**
             * @description Dodatkowe szczegóły (np. zmiana ról jako JSON); może być puste.
             * @example {
             *       "before": [
             *         "ROLE_USER"
             *       ],
             *       "after": [
             *         "ROLE_USER",
             *         "ROLE_ADMIN"
             *       ]
             *     }
             */
            details?: string;
            /**
             * @description Identyfikator korelacji powiązany z logami żądania; może być puste dla zdarzeń spoza kontekstu żądania HTTP.
             * @example f0a1b2c3-d4e5-6789-abcd-ef0123456789
             */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Czas wystąpienia operacji (UTC, ISO-8601).
             * @example 2026-06-20T10:15:30Z
             */
            createdAt: string;
        };
        /** @description Stronicowana lista wpisów audytu. */
        PageAuditLogResponseDto: {
            /** @description Zawartość bieżącej strony. */
            content: components["schemas"]["AuditLogResponseDto"][];
            /**
             * Format: int32
             * @description Numer bieżącej strony (od 0).
             * @example 0
             */
            number: number;
            /**
             * Format: int32
             * @description Rozmiar strony.
             * @example 20
             */
            size: number;
            /**
             * Format: int64
             * @description Łączna liczba elementów.
             * @example 42
             */
            totalElements: number;
            /**
             * Format: int32
             * @description Łączna liczba stron.
             * @example 3
             */
            totalPages: number;
            /**
             * @description Czy to pierwsza strona.
             * @example true
             */
            first: boolean;
            /**
             * @description Czy to ostatnia strona.
             * @example false
             */
            last: boolean;
            /**
             * Format: int32
             * @description Liczba elementów na bieżącej stronie.
             * @example 20
             */
            numberOfElements: number;
            /**
             * @description Czy strona jest pusta.
             * @example false
             */
            empty: boolean;
        };
        /** @description Potwierdzenie usunięcia konta hasłem. */
        DeleteAccountDto: {
            /**
             * @description Hasło użytkownika, wymagane do potwierdzenia usunięcia konta.
             * @example password123
             */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateUserRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identyfikator użytkownika (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRolesDto"];
            };
        };
        responses: {
            /** @description Role zaktualizowane */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Błąd walidacji lub niepoprawny UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiValidationError"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak uprawnień (wymagana rola ROLE_ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Użytkownik nie istnieje (USER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationDto"];
            };
        };
        responses: {
            /** @description Konto utworzone, wiadomość aktywacyjna zaplanowana do wysyłki */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponseDto"];
                };
            };
            /** @description Błąd walidacji danych wejściowych */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiValidationError"];
                };
            };
            /** @description Użytkownik o podanym e-mailu już istnieje (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestDto"];
            };
        };
        responses: {
            /** @description Żądanie przyjęte (niezależnie od istnienia konta) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Błąd walidacji danych wejściowych */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiValidationError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmDto"];
            };
        };
        responses: {
            /** @description Hasło zmienione */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Błąd walidacji danych wejściowych */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiValidationError"];
                };
            };
            /** @description Token nieprawidłowy, wygasły lub już użyty (JWT_BLACKLISTED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Nagłówek z tokenem dostępowym w formacie `Bearer <token>` */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wylogowano; tokeny unieważnione, ciasteczko wyczyszczone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Zalogowano; access token w body, refresh token w ciasteczku */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccessTokenResponseDto"];
                };
            };
            /** @description Błąd walidacji danych wejściowych */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiValidationError"];
                };
            };
            /** @description Nieprawidłowy e-mail lub hasło (INVALID_CREDENTIALS) — jednolita odpowiedź, bez rozróżniania istnienia konta */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Konto nieaktywne — zwracane dopiero po poprawnym uwierzytelnieniu (USER_NOT_ACTIVATED) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    resendActivationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendActivationEmailDto"];
            };
        };
        responses: {
            /** @description Żądanie przyjęte (niezależnie od istnienia/stanu konta) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Błąd walidacji danych wejściowych */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiValidationError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    forceLogout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identyfikator użytkownika (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesje unieważnione (brak treści) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nieprawidłowy format UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak uprawnień (wymagana rola ROLE_ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Użytkownik nie istnieje (USER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdateDto"];
            };
        };
        responses: {
            /** @description Profil zaktualizowany */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponseDto"];
                };
            };
            /** @description Błąd walidacji danych wejściowych */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiValidationError"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identyfikator użytkownika (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Konto dezaktywowane */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Nieprawidłowy format UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak uprawnień (wymagana rola ROLE_ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Użytkownik nie istnieje (USER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    activateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identyfikator użytkownika (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Konto aktywowane */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Nieprawidłowy format UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak uprawnień (wymagana rola ROLE_ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Użytkownik nie istnieje (USER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dane użytkownika */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteOwnAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountDto"];
            };
        };
        responses: {
            /** @description Konto usunięte; tokeny unieważnione, ciasteczko wyczyszczone */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Błąd walidacji danych wejściowych (brak hasła) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiValidationError"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy albo błędne hasło potwierdzenia (INVALID_PASSWORD) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Ostatni administrator nie może usunąć własnego konta (CANNOT_REMOVE_LAST_ADMIN) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie: {
                /** @description Token odświeżający przekazywany automatycznie jako ciasteczko HttpOnly */
                refreshToken: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Wydano nowy access token; nowy refresh token w ciasteczku */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccessTokenResponseDto"];
                };
            };
            /** @description Brak ciasteczka refreshToken (REFRESH_TOKEN_MISSING) albo token odświeżający nieprawidłowy, wygasły lub odwołany */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    activateAccount: {
        parameters: {
            query: {
                /** @description Token aktywacyjny (JWT) z linku w wiadomości e-mail */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Konto aktywowane */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponseDto"];
                };
            };
            /** @description Token nieprawidłowy, wygasły, już użyty (JWT_BLACKLISTED) lub zastąpiony nowszym (TOKEN_REVOKED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identyfikator użytkownika (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Znaleziono użytkownika */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Nieprawidłowy format UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak uprawnień (wymagana rola ROLE_ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Użytkownik nie istnieje (USER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identyfikator użytkownika (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Konto usunięte (brak treści) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Nieprawidłowy format UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak uprawnień (wymagana rola ROLE_ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Użytkownik nie istnieje (USER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getUserByUsername: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Nazwa użytkownika */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Znaleziono użytkownika */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak uprawnień (wymagana rola ROLE_ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Użytkownik nie istnieje (USER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getUserByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Adres e-mail użytkownika */
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Znaleziono użytkownika */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak uprawnień (wymagana rola ROLE_ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Użytkownik nie istnieje (USER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAllUsers: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strona wyników z użytkownikami */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageUserResponseDto"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak uprawnień (wymagana rola ROLE_ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAuditLog: {
        parameters: {
            query: {
                /** @description Filtr: identyfikator (UUID) użytkownika, którego dotyczą operacje */
                targetId?: string;
                /** @description Filtr: e-mail administratora wykonującego operacje */
                actor?: string;
                /** @description Filtr: rodzaj operacji */
                action?: "ACTIVATE" | "DEACTIVATE" | "DELETE" | "FORCE_LOGOUT" | "PASSWORD_CHANGE" | "ROLE_CHANGE";
                /**
                 * @description Filtr: początek zakresu czasu (ISO-8601, UTC), włącznie
                 * @example 2026-06-01T00:00:00Z
                 */
                from?: string;
                /**
                 * @description Filtr: koniec zakresu czasu (ISO-8601, UTC), włącznie
                 * @example 2026-06-30T23:59:59Z
                 */
                to?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strona wyników z wpisami audytu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAuditLogResponseDto"];
                };
            };
            /** @description Nieprawidłowy parametr zapytania (np. zły UUID lub format daty) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak lub nieprawidłowy token dostępowy */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Brak uprawnień (wymagana rola ROLE_ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Błąd wewnętrzny serwera */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
